### ISSUE TITLE
Multiple keyspaces support

### ISSUE THREAD

**Issue by rbino** [vinniefranco/exandra#34]
Hey! I just discovered Exandra while randomly looking to `xandra` dependents on Hex and it seems it would simplify a lot some codebases we're working on, but that would require support for querying across multiple keyspaces.

Right now, I see it's mainly meant to be used with a single keyspace (since a keyspace is required to be passed in `start_link`), but I already verified that it's possible to query tables on other keyspaces by just using

```
from "<keyspace>.<table>"
```

Would it be possible to map the different keyspaces onto [Ecto prefixes](https://hexdocs.pm/ecto/multi-tenancy-with-query-prefixes.html)? From the documentation it seems that MySQL maps them on different databases, which are more or less the equivalents of keyspaces. From the tests it [seems to be supported](https://github.com/vinniefranco/exandra/blob/main/test/exandra/connection_test.exs#L1017) at least in migrations, but passing `prefix: :foo` in `Repo.all` doesn't seem to work (though it sets the prefix on the returned schema).

If you think this is possible and it would be a desirable feature to have, I can try to tackle this with a PR.

**Comment by whatyouhide** [comment]
Yes, I think Ecto prefixes might be the right approach here. I would love a PR 🙃

**Comment by rbino** [comment]
I'm going to take a stab at it then!
